name: Deploy develop

on:
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy to Vercel
        with:
          node_version: 22
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          script_install: pnpm install
          script_build: pnpm build
          preview_output: true
          dist_path: out
          project_name: xaccount-ui
          alias_domain: "xaccount-dev"
          enable_cache: true
          enable_notify_comment: true
          enable_notify_slack: true
          slack_channel: public-ringdao-apps
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

